CREATE TABLE "TQE_API_KEY" (
  "TQE_AK_CODIGO" SERIAL PRIMARY KEY,
  "TQE_AK_BAR_CODIGO" INTEGER NOT NULL REFERENCES "TQE_BARBEARIA"("TQE_BAR_CODIGO"),
  "TQE_AK_NOME" VARCHAR(100) NOT NULL,
  "TQE_AK_KEY_HASH" VARCHAR(255) NOT NULL UNIQUE,
  "TQE_AK_KEY_PREFIX" VARCHAR(10) NOT NULL,
  "TQE_AK_ATIVO" BOOLEAN NOT NULL DEFAULT TRUE,
  "TQE_AK_CRIADO_EM" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "TQE_AK_ULTIMO_USO_EM" TIMESTAMPTZ
);
