-- Força RLS mesmo para o owner da tabela (toqe_app)
-- Sem FORCE, o PostgreSQL deixa o owner bypassar as políticas RLS automaticamente.
-- As políticas foram criadas em 20260507020517_add_rls_policies; esta migration
-- garante que elas sejam aplicadas mesmo quando a conexão usa o role proprietário.

ALTER TABLE "TQE_BARBEARIA" FORCE ROW LEVEL SECURITY;
ALTER TABLE "TQE_MEMBRO_BARBEARIA" FORCE ROW LEVEL SECURITY;
ALTER TABLE "TQE_SERVICO" FORCE ROW LEVEL SECURITY;
ALTER TABLE "TQE_BARBEIRO_SERVICO" FORCE ROW LEVEL SECURITY;
ALTER TABLE "TQE_AGENDAMENTO" FORCE ROW LEVEL SECURITY;
ALTER TABLE "TQE_AGENDAMENTO_ITEM" FORCE ROW LEVEL SECURITY;
ALTER TABLE "TQE_BLOQUEIO_AGENDA" FORCE ROW LEVEL SECURITY;
ALTER TABLE "TQE_JORNADA_TRABALHO" FORCE ROW LEVEL SECURITY;
ALTER TABLE "TQE_NOTIFICACAO_PREFERENCIA" FORCE ROW LEVEL SECURITY;
ALTER TABLE "TQE_TEMA_TENANT" FORCE ROW LEVEL SECURITY;
