-- AlterTable
ALTER TABLE "TQE_BARBEARIA" ADD COLUMN     "TQE_BAR_BARBEIRO_ALTERA_PRECO" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "TQE_BAR_BARBEIRO_CRIA_SERVICO" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "TQE_BARBEIRO_SERVICO" ADD COLUMN     "TQE_BSV_ATIVO" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "TQE_SERVICO" ADD COLUMN     "TQE_SRV_EXCLUSIVO_BARBEIRO_ID" INTEGER;

-- AddForeignKey
ALTER TABLE "TQE_SERVICO" ADD CONSTRAINT "TQE_SERVICO_TQE_SRV_EXCLUSIVO_BARBEIRO_ID_fkey" FOREIGN KEY ("TQE_SRV_EXCLUSIVO_BARBEIRO_ID") REFERENCES "TQE_USUARIO"("TQE_USR_CODIGO") ON DELETE SET NULL ON UPDATE CASCADE;
