-- CreateTable
CREATE TABLE "TQE_PUSH_TOKEN" (
    "TQE_PTK_CODIGO" SERIAL NOT NULL,
    "TQE_PTK_USR_CODIGO" INTEGER NOT NULL,
    "TQE_PTK_TOKEN" VARCHAR(255) NOT NULL,
    "TQE_PTK_PLATAFORMA" VARCHAR(10) NOT NULL DEFAULT 'unknown',
    "TQE_PTK_CRIADO_EM" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TQE_PUSH_TOKEN_pkey" PRIMARY KEY ("TQE_PTK_CODIGO")
);

-- CreateIndex
CREATE UNIQUE INDEX "TQE_PUSH_TOKEN_usrCodigo_token_key" ON "TQE_PUSH_TOKEN"("TQE_PTK_USR_CODIGO", "TQE_PTK_TOKEN");

-- AddForeignKey
ALTER TABLE "TQE_PUSH_TOKEN" ADD CONSTRAINT "TQE_PUSH_TOKEN_TQE_PTK_USR_CODIGO_fkey" FOREIGN KEY ("TQE_PTK_USR_CODIGO") REFERENCES "TQE_USUARIO"("TQE_USR_CODIGO") ON DELETE CASCADE ON UPDATE CASCADE;
