-- DropForeignKey
ALTER TABLE "TQE_AVALIACAO_AGENDAMENTO" DROP CONSTRAINT "TQE_AVALIACAO_AGENDAMENTO_TQE_AVL_AGD_CODIGO_fkey";

-- DropForeignKey
ALTER TABLE "TQE_CONVITE_BARBEARIA" DROP CONSTRAINT "TQE_CONVITE_BARBEARIA_TQE_CVT_BAR_CODIGO_fkey";

-- CreateTable
CREATE TABLE "TQE_CLIENTE_NOTA" (
    "TQE_CLN_CODIGO" SERIAL NOT NULL,
    "TQE_CLN_BAR_CODIGO" INTEGER NOT NULL,
    "TQE_CLN_BARBEIRO_ID" INTEGER NOT NULL,
    "TQE_CLN_CLIENTE_ID" INTEGER NOT NULL,
    "TQE_CLN_CONTEUDO" TEXT NOT NULL,
    "TQE_CLN_CRIADO_EM" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TQE_CLN_ATUALIZADO_EM" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "TQE_CLIENTE_NOTA_pkey" PRIMARY KEY ("TQE_CLN_CODIGO")
);

-- CreateIndex
CREATE UNIQUE INDEX "TQE_CLIENTE_NOTA_TQE_CLN_BAR_CODIGO_TQE_CLN_BARBEIRO_ID_TQE_key" ON "TQE_CLIENTE_NOTA"("TQE_CLN_BAR_CODIGO", "TQE_CLN_BARBEIRO_ID", "TQE_CLN_CLIENTE_ID");

-- AddForeignKey
ALTER TABLE "TQE_CLIENTE_NOTA" ADD CONSTRAINT "TQE_CLIENTE_NOTA_TQE_CLN_BAR_CODIGO_fkey" FOREIGN KEY ("TQE_CLN_BAR_CODIGO") REFERENCES "TQE_BARBEARIA"("TQE_BAR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_CLIENTE_NOTA" ADD CONSTRAINT "TQE_CLIENTE_NOTA_TQE_CLN_BARBEIRO_ID_fkey" FOREIGN KEY ("TQE_CLN_BARBEIRO_ID") REFERENCES "TQE_USUARIO"("TQE_USR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_CLIENTE_NOTA" ADD CONSTRAINT "TQE_CLIENTE_NOTA_TQE_CLN_CLIENTE_ID_fkey" FOREIGN KEY ("TQE_CLN_CLIENTE_ID") REFERENCES "TQE_USUARIO"("TQE_USR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_AVALIACAO_AGENDAMENTO" ADD CONSTRAINT "TQE_AVALIACAO_AGENDAMENTO_TQE_AVL_AGD_CODIGO_fkey" FOREIGN KEY ("TQE_AVL_AGD_CODIGO") REFERENCES "TQE_AGENDAMENTO"("TQE_AGD_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_CONVITE_BARBEARIA" ADD CONSTRAINT "TQE_CONVITE_BARBEARIA_TQE_CVT_BAR_CODIGO_fkey" FOREIGN KEY ("TQE_CVT_BAR_CODIGO") REFERENCES "TQE_BARBEARIA"("TQE_BAR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- RenameIndex
ALTER INDEX "TQE_PUSH_TOKEN_usrCodigo_token_key" RENAME TO "TQE_PUSH_TOKEN_TQE_PTK_USR_CODIGO_TQE_PTK_TOKEN_key";
