-- AlterTable
ALTER TABLE "TQE_BARBEARIA"
  ADD COLUMN IF NOT EXISTS "TQE_BAR_TELEFONE" VARCHAR(30),
  ADD COLUMN IF NOT EXISTS "TQE_BAR_EMAIL"    VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "TQE_BAR_ENDERECO" VARCHAR(200);
