-- Migration: add_avaliacao_convite
-- Adiciona tabelas AvaliacaoAgendamento e ConviteBarbearia

-- 1. Tabela de avaliação de agendamento
CREATE TABLE "TQE_AVALIACAO_AGENDAMENTO" (
  "TQE_AVL_CODIGO"     SERIAL PRIMARY KEY,
  "TQE_AVL_AGD_CODIGO" INTEGER NOT NULL UNIQUE,
  "TQE_AVL_NOTA"       SMALLINT NOT NULL,
  "TQE_AVL_COMENTARIO" TEXT,
  "TQE_AVL_CRIADO_EM"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "TQE_AVALIACAO_AGENDAMENTO_TQE_AVL_AGD_CODIGO_fkey"
    FOREIGN KEY ("TQE_AVL_AGD_CODIGO") REFERENCES "TQE_AGENDAMENTO"("TQE_AGD_CODIGO")
);

-- 2. Tabela de convite de barbearia
CREATE TABLE "TQE_CONVITE_BARBEARIA" (
  "TQE_CVT_CODIGO"     SERIAL PRIMARY KEY,
  "TQE_CVT_TOKEN"      VARCHAR(36) NOT NULL UNIQUE,
  "TQE_CVT_BAR_CODIGO" INTEGER NOT NULL,
  "TQE_CVT_EMAIL"      VARCHAR(100) NOT NULL,
  "TQE_CVT_PERFIL"     VARCHAR(20) NOT NULL DEFAULT 'barbeiro',
  "TQE_CVT_CRIADO_EM"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "TQE_CVT_EXPIRES_AT" TIMESTAMPTZ NOT NULL,
  "TQE_CVT_USADO_EM"   TIMESTAMPTZ,
  CONSTRAINT "TQE_CONVITE_BARBEARIA_TQE_CVT_BAR_CODIGO_fkey"
    FOREIGN KEY ("TQE_CVT_BAR_CODIGO") REFERENCES "TQE_BARBEARIA"("TQE_BAR_CODIGO")
);
