-- CreateTable: contato operacional (sem login, sem e-mail)
CREATE TABLE "TQE_CONTATO" (
    "TQE_CNT_CODIGO"    SERIAL NOT NULL,
    "TQE_CNT_BAR_CODIGO" INTEGER NOT NULL,
    "TQE_CNT_NOME"      VARCHAR(100) NOT NULL,
    "TQE_CNT_TELEFONE"  VARCHAR(20),
    "TQE_CNT_CRIADO_EM" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TQE_CONTATO_pkey" PRIMARY KEY ("TQE_CNT_CODIGO")
);

-- AddForeignKey: contato → barbearia
ALTER TABLE "TQE_CONTATO"
    ADD CONSTRAINT "TQE_CONTATO_TQE_CNT_BAR_CODIGO_fkey"
    FOREIGN KEY ("TQE_CNT_BAR_CODIGO")
    REFERENCES "TQE_BARBEARIA"("TQE_BAR_CODIGO")
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- AlterTable: tornar clienteId nullable em TQE_AGENDAMENTO
ALTER TABLE "TQE_AGENDAMENTO"
    ALTER COLUMN "TQE_AGD_CLIENTE_ID" DROP NOT NULL;

-- AddColumn: contatoId em TQE_AGENDAMENTO
ALTER TABLE "TQE_AGENDAMENTO"
    ADD COLUMN "TQE_AGD_CONTATO_ID" INTEGER;

-- AddForeignKey: agendamento → contato
ALTER TABLE "TQE_AGENDAMENTO"
    ADD CONSTRAINT "TQE_AGENDAMENTO_TQE_AGD_CONTATO_ID_fkey"
    FOREIGN KEY ("TQE_AGD_CONTATO_ID")
    REFERENCES "TQE_CONTATO"("TQE_CNT_CODIGO")
    ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey (manter FK existente clienteId, agora nullable)
-- Nota: a FK TQE_AGD_CLIENTE_ID → TQE_USUARIO já existia; só o NOT NULL foi removido.

-- Constraint XOR: exatamente um de clienteId / contatoId deve estar preenchido.
-- O Prisma não suporta CHECK nativamente — mantida como SQL puro na migration.
ALTER TABLE "TQE_AGENDAMENTO"
    ADD CONSTRAINT "TQE_AGD_PESSOA_XOR"
    CHECK (
        ("TQE_AGD_CLIENTE_ID" IS NOT NULL AND "TQE_AGD_CONTATO_ID" IS NULL) OR
        ("TQE_AGD_CLIENTE_ID" IS NULL  AND "TQE_AGD_CONTATO_ID" IS NOT NULL)
    );
