-- CreateTable
CREATE TABLE "TQE_PONTO_FIDELIDADE" (
    "TQE_PF_CODIGO" SERIAL NOT NULL,
    "TQE_PF_BAR_CODIGO" INTEGER NOT NULL,
    "TQE_PF_CLI_CODIGO" INTEGER NOT NULL,
    "TQE_PF_PONTOS" INTEGER NOT NULL,
    "TQE_PF_TIPO" VARCHAR(20) NOT NULL,
    "TQE_PF_AGD_CODIGO" INTEGER,
    "TQE_PF_CRIADO_EM" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TQE_PONTO_FIDELIDADE_pkey" PRIMARY KEY ("TQE_PF_CODIGO"),
    CONSTRAINT "TQE_PONTO_FIDELIDADE_tipo_check" CHECK ("TQE_PF_TIPO" IN ('ganho', 'resgate'))
);

-- AlterTable
ALTER TABLE "TQE_USUARIO" ADD COLUMN IF NOT EXISTS "TQE_USR_PONTOS_ACUMULADOS" INTEGER NOT NULL DEFAULT 0;

-- AddForeignKey
ALTER TABLE "TQE_PONTO_FIDELIDADE" ADD CONSTRAINT "TQE_PONTO_FIDELIDADE_TQE_PF_BAR_CODIGO_fkey" FOREIGN KEY ("TQE_PF_BAR_CODIGO") REFERENCES "TQE_BARBEARIA"("TQE_BAR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_PONTO_FIDELIDADE" ADD CONSTRAINT "TQE_PONTO_FIDELIDADE_TQE_PF_CLI_CODIGO_fkey" FOREIGN KEY ("TQE_PF_CLI_CODIGO") REFERENCES "TQE_USUARIO"("TQE_USR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_PONTO_FIDELIDADE" ADD CONSTRAINT "TQE_PONTO_FIDELIDADE_TQE_PF_AGD_CODIGO_fkey" FOREIGN KEY ("TQE_PF_AGD_CODIGO") REFERENCES "TQE_AGENDAMENTO"("TQE_AGD_CODIGO") ON DELETE SET NULL ON UPDATE CASCADE;
