-- CreateTable
CREATE TABLE "TQE_PASSWORD_RESET_TOKEN" (
    "TQE_PRT_CODIGO" SERIAL NOT NULL,
    "TQE_PRT_USR_CODIGO" INTEGER NOT NULL,
    "TQE_PRT_TOKEN" VARCHAR(100) NOT NULL,
    "TQE_PRT_EXPIRA_EM" TIMESTAMPTZ NOT NULL,
    "TQE_PRT_USADO_EM" TIMESTAMPTZ,
    "TQE_PRT_CRIADO_EM" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "TQE_PASSWORD_RESET_TOKEN_pkey" PRIMARY KEY ("TQE_PRT_CODIGO")
);
CREATE UNIQUE INDEX "TQE_PASSWORD_RESET_TOKEN_TQE_PRT_TOKEN_key" ON "TQE_PASSWORD_RESET_TOKEN"("TQE_PRT_TOKEN");
ALTER TABLE "TQE_PASSWORD_RESET_TOKEN" ADD CONSTRAINT "TQE_PASSWORD_RESET_TOKEN_TQE_PRT_USR_CODIGO_fkey" FOREIGN KEY ("TQE_PRT_USR_CODIGO") REFERENCES "TQE_USUARIO"("TQE_USR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;
