-- CreateTable
CREATE TABLE "TQE_USUARIO" (
    "TQE_USR_CODIGO" SERIAL NOT NULL,
    "TQE_USR_NOME" VARCHAR(100) NOT NULL,
    "TQE_USR_EMAIL" VARCHAR(100) NOT NULL,
    "TQE_USR_SENHA_HASH" VARCHAR(255) NOT NULL,
    "TQE_USR_TELEFONE" VARCHAR(20),
    "TQE_USR_AVATAR_URL" TEXT,
    "TQE_USR_ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "TQE_USR_CRIADO_EM" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TQE_USUARIO_pkey" PRIMARY KEY ("TQE_USR_CODIGO")
);

-- CreateTable
CREATE TABLE "TQE_REFRESH_TOKEN" (
    "TQE_RTK_CODIGO" SERIAL NOT NULL,
    "TQE_RTK_USR_CODIGO" INTEGER NOT NULL,
    "TQE_RTK_HASH" VARCHAR(255) NOT NULL,
    "TQE_RTK_EXPIRA_EM" TIMESTAMPTZ NOT NULL,
    "TQE_RTK_REVOGADO" BOOLEAN NOT NULL DEFAULT false,
    "TQE_RTK_CRIADO_EM" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TQE_REFRESH_TOKEN_pkey" PRIMARY KEY ("TQE_RTK_CODIGO")
);

-- CreateTable
CREATE TABLE "TQE_BARBEARIA" (
    "TQE_BAR_CODIGO" SERIAL NOT NULL,
    "TQE_BAR_NOME" VARCHAR(100) NOT NULL,
    "TQE_BAR_SLUG" VARCHAR(60) NOT NULL,
    "TQE_BAR_TIMEZONE" TEXT NOT NULL DEFAULT 'America/Sao_Paulo',
    "TQE_BAR_PLANO" TEXT NOT NULL DEFAULT 'free',
    "TQE_BAR_PLANO_STATUS" TEXT NOT NULL DEFAULT 'ativo',
    "TQE_BAR_BLOQUEADA_EM" TIMESTAMPTZ,
    "TQE_BAR_ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "TQE_BAR_CRIADO_EM" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TQE_BARBEARIA_pkey" PRIMARY KEY ("TQE_BAR_CODIGO")
);

-- CreateTable
CREATE TABLE "TQE_MEMBRO_BARBEARIA" (
    "TQE_MBR_CODIGO" SERIAL NOT NULL,
    "TQE_MBR_BAR_CODIGO" INTEGER NOT NULL,
    "TQE_MBR_USR_CODIGO" INTEGER NOT NULL,
    "TQE_MBR_PERFIL" VARCHAR(20) NOT NULL,
    "TQE_MBR_CRIADO_EM" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TQE_MEMBRO_BARBEARIA_pkey" PRIMARY KEY ("TQE_MBR_CODIGO")
);

-- CreateTable
CREATE TABLE "TQE_TEMA_TENANT" (
    "TQE_TEM_CODIGO" SERIAL NOT NULL,
    "TQE_TEM_BAR_CODIGO" INTEGER NOT NULL,
    "TQE_TEM_COR_PRIMARIA" VARCHAR(7),
    "TQE_TEM_COR_FUNDO" VARCHAR(7),
    "TQE_TEM_LOGO_URL" TEXT,
    "TQE_TEM_SUBDOMINIO" VARCHAR(60),

    CONSTRAINT "TQE_TEMA_TENANT_pkey" PRIMARY KEY ("TQE_TEM_CODIGO")
);

-- CreateTable
CREATE TABLE "TQE_PLANO_LIMITE" (
    "TQE_PLI_CODIGO" SERIAL NOT NULL,
    "TQE_PLI_PLANO" VARCHAR(20) NOT NULL,
    "TQE_PLI_MAX_BARBEIROS" INTEGER,
    "TQE_PLI_MAX_AGD_MES" INTEGER,
    "TQE_PLI_WHITE_LABEL" BOOLEAN NOT NULL DEFAULT false,
    "TQE_PLI_API_PUBLICA" BOOLEAN NOT NULL DEFAULT false,
    "TQE_PLI_RELATORIOS_ADV" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "TQE_PLANO_LIMITE_pkey" PRIMARY KEY ("TQE_PLI_CODIGO")
);

-- CreateTable
CREATE TABLE "TQE_SERVICO" (
    "TQE_SRV_CODIGO" SERIAL NOT NULL,
    "TQE_SRV_BAR_CODIGO" INTEGER NOT NULL,
    "TQE_SRV_NOME" VARCHAR(100) NOT NULL,
    "TQE_SRV_PRECO_BASE" DECIMAL(10,2),
    "TQE_SRV_DURACAO_BASE" INTEGER,
    "TQE_SRV_ATIVO" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "TQE_SERVICO_pkey" PRIMARY KEY ("TQE_SRV_CODIGO")
);

-- CreateTable
CREATE TABLE "TQE_BARBEIRO_SERVICO" (
    "TQE_BSV_CODIGO" SERIAL NOT NULL,
    "TQE_BSV_BAR_CODIGO" INTEGER NOT NULL,
    "TQE_BSV_BARBEIRO_ID" INTEGER NOT NULL,
    "TQE_BSV_SRV_CODIGO" INTEGER NOT NULL,
    "TQE_BSV_DURACAO_MIN" INTEGER NOT NULL,
    "TQE_BSV_PRECO_PROPRIO" DECIMAL(10,2),

    CONSTRAINT "TQE_BARBEIRO_SERVICO_pkey" PRIMARY KEY ("TQE_BSV_CODIGO")
);

-- CreateTable
CREATE TABLE "TQE_AGENDAMENTO" (
    "TQE_AGD_CODIGO" SERIAL NOT NULL,
    "TQE_AGD_BAR_CODIGO" INTEGER NOT NULL,
    "TQE_AGD_BARBEIRO_ID" INTEGER NOT NULL,
    "TQE_AGD_CLIENTE_ID" INTEGER NOT NULL,
    "TQE_AGD_INICIO" TIMESTAMPTZ NOT NULL,
    "TQE_AGD_FIM" TIMESTAMPTZ NOT NULL,
    "TQE_AGD_STATUS" VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    "TQE_AGD_TIPO" VARCHAR(20) NOT NULL DEFAULT 'AGENDADO',
    "TQE_AGD_OBSERVACAO" TEXT,
    "TQE_AGD_CRIADO_EM" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TQE_AGENDAMENTO_pkey" PRIMARY KEY ("TQE_AGD_CODIGO")
);

-- CreateTable
CREATE TABLE "TQE_AGENDAMENTO_ITEM" (
    "TQE_AGI_CODIGO" SERIAL NOT NULL,
    "TQE_AGI_BAR_CODIGO" INTEGER NOT NULL,
    "TQE_AGI_AGD_CODIGO" INTEGER NOT NULL,
    "TQE_AGI_SRV_CODIGO" INTEGER NOT NULL,
    "TQE_AGI_DURACAO_MIN" INTEGER NOT NULL,
    "TQE_AGI_PRECO" DECIMAL(10,2) NOT NULL,
    "TQE_AGI_ORDEM" SMALLINT NOT NULL DEFAULT 1,

    CONSTRAINT "TQE_AGENDAMENTO_ITEM_pkey" PRIMARY KEY ("TQE_AGI_CODIGO")
);

-- CreateTable
CREATE TABLE "TQE_BLOQUEIO_AGENDA" (
    "TQE_BLA_CODIGO" SERIAL NOT NULL,
    "TQE_BLA_BAR_CODIGO" INTEGER NOT NULL,
    "TQE_BLA_BARBEIRO_ID" INTEGER NOT NULL,
    "TQE_BLA_INICIO" TIMESTAMPTZ NOT NULL,
    "TQE_BLA_FIM" TIMESTAMPTZ NOT NULL,
    "TQE_BLA_MOTIVO" VARCHAR(100),
    "TQE_BLA_RECORRENTE" BOOLEAN NOT NULL DEFAULT false,
    "TQE_BLA_CRIADO_EM" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TQE_BLOQUEIO_AGENDA_pkey" PRIMARY KEY ("TQE_BLA_CODIGO")
);

-- CreateTable
CREATE TABLE "TQE_JORNADA_TRABALHO" (
    "TQE_JOR_CODIGO" SERIAL NOT NULL,
    "TQE_JOR_BAR_CODIGO" INTEGER NOT NULL,
    "TQE_JOR_BARBEIRO_ID" INTEGER NOT NULL,
    "TQE_JOR_DIA_SEMANA" SMALLINT NOT NULL,
    "TQE_JOR_INICIO" TEXT NOT NULL,
    "TQE_JOR_FIM" TEXT NOT NULL,
    "TQE_JOR_ALMOCO_INI" TEXT,
    "TQE_JOR_ALMOCO_FIM" TEXT,
    "TQE_JOR_ATIVO" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "TQE_JORNADA_TRABALHO_pkey" PRIMARY KEY ("TQE_JOR_CODIGO")
);

-- CreateTable
CREATE TABLE "TQE_NOTIFICACAO_PREFERENCIA" (
    "TQE_NPR_CODIGO" SERIAL NOT NULL,
    "TQE_NPR_BAR_CODIGO" INTEGER NOT NULL,
    "TQE_NPR_USR_CODIGO" INTEGER NOT NULL,
    "TQE_NPR_CANAL" VARCHAR(20) NOT NULL,
    "TQE_NPR_ATIVO" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "TQE_NOTIFICACAO_PREFERENCIA_pkey" PRIMARY KEY ("TQE_NPR_CODIGO")
);

-- CreateIndex
CREATE UNIQUE INDEX "TQE_USUARIO_TQE_USR_EMAIL_key" ON "TQE_USUARIO"("TQE_USR_EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "TQE_USUARIO_TQE_USR_TELEFONE_key" ON "TQE_USUARIO"("TQE_USR_TELEFONE");

-- CreateIndex
CREATE UNIQUE INDEX "TQE_BARBEARIA_TQE_BAR_SLUG_key" ON "TQE_BARBEARIA"("TQE_BAR_SLUG");

-- CreateIndex
CREATE UNIQUE INDEX "TQE_MEMBRO_BARBEARIA_TQE_MBR_BAR_CODIGO_TQE_MBR_USR_CODIGO_key" ON "TQE_MEMBRO_BARBEARIA"("TQE_MBR_BAR_CODIGO", "TQE_MBR_USR_CODIGO");

-- CreateIndex
CREATE UNIQUE INDEX "TQE_TEMA_TENANT_TQE_TEM_BAR_CODIGO_key" ON "TQE_TEMA_TENANT"("TQE_TEM_BAR_CODIGO");

-- CreateIndex
CREATE UNIQUE INDEX "TQE_PLANO_LIMITE_TQE_PLI_PLANO_key" ON "TQE_PLANO_LIMITE"("TQE_PLI_PLANO");

-- CreateIndex
CREATE UNIQUE INDEX "TQE_BARBEIRO_SERVICO_TQE_BSV_BARBEIRO_ID_TQE_BSV_SRV_CODIGO_key" ON "TQE_BARBEIRO_SERVICO"("TQE_BSV_BARBEIRO_ID", "TQE_BSV_SRV_CODIGO");

-- AddForeignKey
ALTER TABLE "TQE_REFRESH_TOKEN" ADD CONSTRAINT "TQE_REFRESH_TOKEN_TQE_RTK_USR_CODIGO_fkey" FOREIGN KEY ("TQE_RTK_USR_CODIGO") REFERENCES "TQE_USUARIO"("TQE_USR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_MEMBRO_BARBEARIA" ADD CONSTRAINT "TQE_MEMBRO_BARBEARIA_TQE_MBR_BAR_CODIGO_fkey" FOREIGN KEY ("TQE_MBR_BAR_CODIGO") REFERENCES "TQE_BARBEARIA"("TQE_BAR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_MEMBRO_BARBEARIA" ADD CONSTRAINT "TQE_MEMBRO_BARBEARIA_TQE_MBR_USR_CODIGO_fkey" FOREIGN KEY ("TQE_MBR_USR_CODIGO") REFERENCES "TQE_USUARIO"("TQE_USR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_TEMA_TENANT" ADD CONSTRAINT "TQE_TEMA_TENANT_TQE_TEM_BAR_CODIGO_fkey" FOREIGN KEY ("TQE_TEM_BAR_CODIGO") REFERENCES "TQE_BARBEARIA"("TQE_BAR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_SERVICO" ADD CONSTRAINT "TQE_SERVICO_TQE_SRV_BAR_CODIGO_fkey" FOREIGN KEY ("TQE_SRV_BAR_CODIGO") REFERENCES "TQE_BARBEARIA"("TQE_BAR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_BARBEIRO_SERVICO" ADD CONSTRAINT "TQE_BARBEIRO_SERVICO_TQE_BSV_BAR_CODIGO_fkey" FOREIGN KEY ("TQE_BSV_BAR_CODIGO") REFERENCES "TQE_BARBEARIA"("TQE_BAR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_BARBEIRO_SERVICO" ADD CONSTRAINT "TQE_BARBEIRO_SERVICO_TQE_BSV_BARBEIRO_ID_fkey" FOREIGN KEY ("TQE_BSV_BARBEIRO_ID") REFERENCES "TQE_USUARIO"("TQE_USR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_BARBEIRO_SERVICO" ADD CONSTRAINT "TQE_BARBEIRO_SERVICO_TQE_BSV_SRV_CODIGO_fkey" FOREIGN KEY ("TQE_BSV_SRV_CODIGO") REFERENCES "TQE_SERVICO"("TQE_SRV_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_AGENDAMENTO" ADD CONSTRAINT "TQE_AGENDAMENTO_TQE_AGD_BAR_CODIGO_fkey" FOREIGN KEY ("TQE_AGD_BAR_CODIGO") REFERENCES "TQE_BARBEARIA"("TQE_BAR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_AGENDAMENTO" ADD CONSTRAINT "TQE_AGENDAMENTO_TQE_AGD_BARBEIRO_ID_fkey" FOREIGN KEY ("TQE_AGD_BARBEIRO_ID") REFERENCES "TQE_USUARIO"("TQE_USR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_AGENDAMENTO" ADD CONSTRAINT "TQE_AGENDAMENTO_TQE_AGD_CLIENTE_ID_fkey" FOREIGN KEY ("TQE_AGD_CLIENTE_ID") REFERENCES "TQE_USUARIO"("TQE_USR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_AGENDAMENTO_ITEM" ADD CONSTRAINT "TQE_AGENDAMENTO_ITEM_TQE_AGI_BAR_CODIGO_fkey" FOREIGN KEY ("TQE_AGI_BAR_CODIGO") REFERENCES "TQE_BARBEARIA"("TQE_BAR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_AGENDAMENTO_ITEM" ADD CONSTRAINT "TQE_AGENDAMENTO_ITEM_TQE_AGI_AGD_CODIGO_fkey" FOREIGN KEY ("TQE_AGI_AGD_CODIGO") REFERENCES "TQE_AGENDAMENTO"("TQE_AGD_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_AGENDAMENTO_ITEM" ADD CONSTRAINT "TQE_AGENDAMENTO_ITEM_TQE_AGI_SRV_CODIGO_fkey" FOREIGN KEY ("TQE_AGI_SRV_CODIGO") REFERENCES "TQE_SERVICO"("TQE_SRV_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_BLOQUEIO_AGENDA" ADD CONSTRAINT "TQE_BLOQUEIO_AGENDA_TQE_BLA_BAR_CODIGO_fkey" FOREIGN KEY ("TQE_BLA_BAR_CODIGO") REFERENCES "TQE_BARBEARIA"("TQE_BAR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_BLOQUEIO_AGENDA" ADD CONSTRAINT "TQE_BLOQUEIO_AGENDA_TQE_BLA_BARBEIRO_ID_fkey" FOREIGN KEY ("TQE_BLA_BARBEIRO_ID") REFERENCES "TQE_USUARIO"("TQE_USR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_JORNADA_TRABALHO" ADD CONSTRAINT "TQE_JORNADA_TRABALHO_TQE_JOR_BAR_CODIGO_fkey" FOREIGN KEY ("TQE_JOR_BAR_CODIGO") REFERENCES "TQE_BARBEARIA"("TQE_BAR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_JORNADA_TRABALHO" ADD CONSTRAINT "TQE_JORNADA_TRABALHO_TQE_JOR_BARBEIRO_ID_fkey" FOREIGN KEY ("TQE_JOR_BARBEIRO_ID") REFERENCES "TQE_USUARIO"("TQE_USR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_NOTIFICACAO_PREFERENCIA" ADD CONSTRAINT "TQE_NOTIFICACAO_PREFERENCIA_TQE_NPR_BAR_CODIGO_fkey" FOREIGN KEY ("TQE_NPR_BAR_CODIGO") REFERENCES "TQE_BARBEARIA"("TQE_BAR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TQE_NOTIFICACAO_PREFERENCIA" ADD CONSTRAINT "TQE_NOTIFICACAO_PREFERENCIA_TQE_NPR_USR_CODIGO_fkey" FOREIGN KEY ("TQE_NPR_USR_CODIGO") REFERENCES "TQE_USUARIO"("TQE_USR_CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE;
