-- CreateTable
CREATE TABLE "TQE_HORARIO_FUNCIONAMENTO" (
    "TQE_HFN_CODIGO" SERIAL NOT NULL,
    "TQE_HFN_BAR_CODIGO" INTEGER NOT NULL,
    "TQE_HFN_DIA_SEMANA" SMALLINT NOT NULL,
    "TQE_HFN_ABERTO" BOOLEAN NOT NULL DEFAULT true,
    "TQE_HFN_ABERTURA" VARCHAR(5) NOT NULL,
    "TQE_HFN_FECHAMENTO" VARCHAR(5) NOT NULL,

    CONSTRAINT "TQE_HORARIO_FUNCIONAMENTO_pkey" PRIMARY KEY ("TQE_HFN_CODIGO")
);

-- CreateIndex
CREATE UNIQUE INDEX "TQE_HORARIO_FUNCIONAMENTO_TQE_HFN_BAR_CODIGO_TQE_HFN_DIA_SE_key" ON "TQE_HORARIO_FUNCIONAMENTO"("TQE_HFN_BAR_CODIGO", "TQE_HFN_DIA_SEMANA");

-- AddForeignKey
ALTER TABLE "TQE_HORARIO_FUNCIONAMENTO" ADD CONSTRAINT "TQE_HORARIO_FUNCIONAMENTO_TQE_HFN_BAR_CODIGO_fkey" FOREIGN KEY ("TQE_HFN_BAR_CODIGO") REFERENCES "TQE_BARBEARIA"("TQE_BAR_CODIGO") ON DELETE CASCADE ON UPDATE CASCADE;
